services:
  - name: backend
    app_name: transendence
    repo: backend
    port: 3000
    target_group: backend
    secrets_manager_name: "JWT_EXPIRES_IN/JWT_SECRET/DEFAULT_AVATAR"
    secrets:
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - DEFAULT_AVATAR
      - DATABASE_URL
    vpc: transendence
    role_name: ecs-task
    cluster: transendence
    daemon: True


  - name: frontend
    app_name: transendence
    repo: frontend
    port: 80
    target_group: frontend
    vpc: transendence
    role_name: ecs-task
    cluster: transendence
    daemon: True


