security_groups:
  - name: ecs-sg
    app_name: transendence
    description: SG for ECS
    allow_all_outbound: true
    ingress: []
    vpc: transendence

  - name: db-sg
    app_name: transendence
    description: SG for RDS
    allow_all_outbound: true
    ingress:
      - protocol: tcp
        port: 5432
        source_sg: ecs-sg
        description: PostgreSQL from ECS
    vpc: transendence

  - name: alb-sg
    app_name: transendence
    description: SG for ALB
    vpc: transendence
    allow_all_outbound: true
    ingress:
      - protocol: tcp
        port: 80
        source_sg: 0.0.0.0/0
        description: HTTP access from public

      - protocol: tcp
        port: 443
        source_sg: 0.0.0.0/0
        description: HTTPS access from public

  - name: ec2-alb
    app_name: transendence
    description: SG for EC2 behind ALB
    vpc: transendence
    allow_all_outbound: true
    ingress:
      - protocol: tcp
        port: 3000
        source_sg: alb-sg 
        description: Allow ALB to access EC2 on port 3000
