security_groups:
  - name: lambda-sg
    app_name: transendence
    description: SG for Lambda Functions
    allow_all_outbound: true
    ingress: []
    vpc: transendence

  - name: bastion-sg
    app_name: transendence
    description: SG for Bastion Host
    allow_all_outbound: true
    ingress:
      - protocol: tcp
        port: 22
        source: "0.0.0.0/0"
        description: SSH Access
    vpc: transendence

  - name: ecs-sg
    app_name: transendence
    description: SG for ECS
    allow_all_outbound: true
    ingress: []
    vpc: transendence

  - name: db-sg
    app_name: transendence
    description: SG for RDS
    allow_all_outbound: true
    ingress:
      - protocol: tcp
        port: 5432
        source_sg: ecs-sg
        description: PostgreSQL from ECS
    vpc: transendence
