alb:
  - name: transendence-alb
    endpoint_ssm: "/transendence/alb/arn"
    redirect_http: true

    route53:
      domain_name: dev.yospace.ai
      subdomain: transendence
      alb_arn: transendence-alb

    services:
      - name: frontend
      - name: backend

    target_groups:
      frontend:
        port: 80
        health_path: /
      backend:
        port: 3000
        health_path: /api/health

    routing:
      - name: ApiRoute
        priority: 1
        path: "/api/*"
        target: backend

      - name: AvatarsRoute
        priority: 2
        path: "/avatars/*"
        target: backend

      - name: DefaultRoute
        priority: 10
        path: "/*"
        target: frontend
    vpc: transendence
    cluster: transendence-cluster
    certificate: transendence-dev-cert
