roles:
  - name: ecs-task
    app_name: transendence
    description: ECS task role for app
    service: ecs-tasks.amazonaws.com
    managed_policies:
      - AmazonS3ReadOnlyAccess
      - SecretsManagerReadWrite
